name: TruffleHog OSS

on:
  push:

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3.5.2

    - name: Run TruffleHog
      uses: trufflesecurity/trufflehog@v3.34.0
